version: '3'
services:
  kubectl128:
    build:
      context: .
    image: chatwork/kubectl
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/kubectl tail -f /dev/null
    container_name: kubectl128
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kubectl128
